### ISSUE TITLE
'MaterialDescriptor' does not contain a definiton for 'ShaderName' (happens on Unity 2021.3.15f1 and 2022.2.0f1)

### ISSUE THREAD

**Issue by ghost** [simplestargame/SimpleURPToonLitOutlineExample#4]
Hi! Implemented UniVRM and your SimpleURPToonLitOutlineExample into Unity and came across a red error after replacing the MaterialFactory.cs :

`Assets\VRMShaders\GLTF\IO\Runtime\Material\Importer\MaterialFactory.cs(109,38): error CS1061: 'MaterialDescriptor' does not contain a definition for 'ShaderName' and no accessible extension method 'ShaderName' accepting a first argument of type 'MaterialDescriptor' could be found (are you missing a using directive or an assembly reference?)`

Any clue on how to fix this? I checked the **MaterialDescriptor.cs** and changed the

**var shaderName = matDesc.ShaderName** 

to 

**var shaderName = matDesc.Name**

inside the **MaterialFactory.cs** and it fixed the error but brought another red error in **ImporterContext.cs** (shown below). 
I'm probably not supposed to do this but thought I'd let you know about this anyway. 

`Assets\UniGLTF\Runtime\UniGLTF\IO\ImporterContext.cs(50,35): error CS7036: There is no argument given that corresponds to the required formal parameter 'fallbackShaders' of 'MaterialFactory.MaterialFactory(IReadOnlyDictionary<SubAssetKey, Material>, IReadOnlyDictionary<string, string>)'
`

**Comment by simplestargame** [comment]
What version of UniVRM do you use?

**Comment by ghost** [comment]
> What version of UniVRM do you use?

Sorry! Forgot to mention that. The latest v0.108.0 UniVRM-0.108.0_e16d.unitypackage

**Comment by ghost** [comment]
Realized now that I should use my brain to read more carefully. I just noticed your shader is for the 106 version and I was trying with the latest UniVRM lol

I am deeply sorry for the trouble 

Much love for the shaders boss. They look amazing :)
