### ISSUE TITLE
Error when import package

### ISSUE THREAD

**Issue by willemdoll** [simplestargame/SimpleURPToonLitOutlineExample#6]
Errors when importing the package, did everything according to the instructions. Unity 2021.3.16f1 LTS.

Assets\SimplestarGame\SimpleURPToonLitOutlineExample\Scripts\MaterialFactory.cs(12,36): error CS0246: The type or namespace name 'IResponsibilityForDestroyObjects' could not be found (are you missing a using directive or an assembly reference?)

Assets\SimplestarGame\SimpleURPToonLitOutlineExample\Scripts\MaterialFactory.cs(25,20): error CS0246: The type or namespace name 'SubAssetKey' could not be found (are you missing a using directive or an assembly reference?)

**Comment by willemdoll** [comment]
Assets\SimplestarGame\SimpleURPToonLitOutlineExample\Scripts\MaterialFactory.cs(109,38): error CS1061: 'MaterialDescriptor' does not contain a definition for 'ShaderName' and no accessible extension method 'ShaderName' accepting a first argument of type 'MaterialDescriptor' could be found (are you missing a using directive or an assembly reference?)

**Comment by simplestargame** [comment]
What version of UniVRM do you use?

**Comment by willemdoll** [comment]
UniVRM-0.108.0_e16d

**Comment by willemdoll** [comment]
Yeah.. my bad, did not check for which version, apparently I'm already too tired. But thanks for the quick response, its ok now.

**Comment by simplestargame** [comment]
I have created a package for UniVRM-0.108.0. You can use it if you like.
https://github.com/simplestargame/SimpleURPToonLitOutlineExample/releases/tag/UniVRM-0.108.0

**Comment by willemdoll** [comment]
Oh my god, you're the best, thanks!
